name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
  test-axios-action:
        name: 'Perform REST API Test'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                repository: marcelodebittencourt/YieldStreet_APIAutomationTest_JS_Axios
                path: YieldStreet_APIAutomationTest_JS_Axios
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                node-version: 14.x
            - run: |
                npm install
                npm test,  
            working-directory: ./YieldStreet_APIAutomationTest_JS_Axios       